### PR TITLE
Fix ES9 typo

### PR DESCRIPTION
**Pull request by ra100**
I believe this is just a typo.

### CODE REVIEW

**Comment by daumann** [comment]
I wonder if we should get rid of ES9 term altogether and just call it ES2018 everywhere?

**Comment by ra100** [comment]
Yup, using ES[number] and ES[year] is confusing, I guess, and the first one was deprecated already, right?

**Comment by daumann** [comment]
Yes. Only ES6 is an official naming convention, ES7 and onwards it is by years. However, in the wild (or Wikipedia) the old naming convention is still used.

**Comment by daumann** [comment]
WIll merge for now, we can do the replacement later.

**Pull request merged**
